Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 1107, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 852, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
airborne_ir = xr.open_rasterio('/tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    198[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 199[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mself[0m[0;34m.[0m[0m_key[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    200[0m             [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/lru_cache.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     52[0m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0m_lock[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 53[0;31m             [0mvalue[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     54[0m             [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m.[0m[0mmove_to_end[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: [<function open at 0x7f4d93850550>, ('/tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif',), 'r', ()]

During handling of the above exception, another exception occurred:

[0;31mCPLE_OpenFailedError[0m                      Traceback (most recent call last)
[0;32mrasterio/_base.pyx[0m in [0;36mrasterio._base.DatasetBase.__init__[0;34m()[0m

[0;32mrasterio/_shim.pyx[0m in [0;36mrasterio._shim.open_dataset[0;34m()[0m

[0;32mrasterio/_err.pyx[0m in [0;36mrasterio._err.exc_wrap_pointer[0;34m()[0m

[0;31mCPLE_OpenFailedError[0m: /tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mRasterioIOError[0m                           Traceback (most recent call last)
[0;32m<ipython-input-3-206612193a33>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mairborne_ir[0m [0;34m=[0m [0mxr[0m[0;34m.[0m[0mopen_rasterio[0m[0;34m([0m[0;34m'/tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/rasterio_.py[0m in [0;36mopen_rasterio[0;34m(filename, parse_coordinates, chunks, cache, lock)[0m
[1;32m    274[0m [0;34m[0m[0m
[1;32m    275[0m     [0mmanager[0m [0;34m=[0m [0mCachingFileManager[0m[0;34m([0m[0mrasterio[0m[0;34m.[0m[0mopen[0m[0;34m,[0m [0mfilename[0m[0;34m,[0m [0mlock[0m[0;34m=[0m[0mlock[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0;34m"r"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 276[0;31m     [0mriods[0m [0;34m=[0m [0mmanager[0m[0;34m.[0m[0macquire[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    277[0m     [0;32mif[0m [0mvrt_params[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    278[0m         [0mriods[0m [0;34m=[0m [0mWarpedVRT[0m[0;34m([0m[0mriods[0m[0;34m,[0m [0;34m**[0m[0mvrt_params[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36macquire[0;34m(self, needs_lock)[0m
[1;32m    179[0m             [0mAn[0m [0mopen[0m [0mfile[0m [0mobject[0m[0;34m,[0m [0;32mas[0m [0mreturned[0m [0mby[0m[0;31m [0m[0;31m`[0m[0;31m`[0m[0mopener[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;31m`[0m[0;31m`[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    180[0m         """
[0;32m--> 181[0;31m         [0mfile[0m[0;34m,[0m [0m_[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_acquire_with_cache_info[0m[0;34m([0m[0mneeds_lock[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    182[0m         [0;32mreturn[0m [0mfile[0m[0;34m[0m[0;34m[0m[0m
[1;32m    183[0m [0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    203[0m                     [0mkwargs[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mcopy[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    204[0m                     [0mkwargs[0m[0;34m[[0m[0;34m"mode"[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_mode[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 205[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_opener[0m[0;34m([0m[0;34m*[0m[0mself[0m[0;34m.[0m[0m_args[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    206[0m                 [0;32mif[0m [0mself[0m[0;34m.[0m[0m_mode[0m [0;34m==[0m [0;34m"w"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    207[0m                     [0;31m# ensure file doesn't get overriden when opened again[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/rasterio/env.py[0m in [0;36mwrapper[0;34m(*args, **kwds)[0m
[1;32m    433[0m [0;34m[0m[0m
[1;32m    434[0m         [0;32mwith[0m [0menv_ctor[0m[0;34m([0m[0msession[0m[0;34m=[0m[0msession[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 435[0;31m             [0;32mreturn[0m [0mf[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    436[0m [0;34m[0m[0m
[1;32m    437[0m     [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m/srv/conda/envs/notebook/lib/python3.8/site-packages/rasterio/__init__.py[0m in [0;36mopen[0;34m(fp, mode, driver, width, height, count, crs, transform, dtype, nodata, sharing, **kwargs)[0m
[1;32m    218[0m         [0;31m# None.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    219[0m         [0;32mif[0m [0mmode[0m [0;34m==[0m [0;34m'r'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 220[0;31m             [0ms[0m [0;34m=[0m [0mDatasetReader[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mdriver[0m[0;34m=[0m[0mdriver[0m[0;34m,[0m [0msharing[0m[0;34m=[0m[0msharing[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    221[0m         [0;32melif[0m [0mmode[0m [0;34m==[0m [0;34m"r+"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    222[0m             s = get_writer_for_path(path, driver=driver)(

[0;32mrasterio/_base.pyx[0m in [0;36mrasterio._base.DatasetBase.__init__[0;34m()[0m

[0;31mRasterioIOError[0m: /tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif: No such file or directory
RasterioIOError: /tmp/thermal-ir/SNOWEX2020_IR_PLANE_2020Feb08_mosaicked_2020-02-08T181915.tif: No such file or directory

